### ISSUE TITLE
希望将μtorrent 3.5.5加入允许列表

### ISSUE THREAD

**Issue by inntechy** [sysu-ipv6/sysupt#16]
~~因为我在用3.5.5（逃~~
3.5.5许多pt站都支持，希望能把这个版本支持一下

**Comment by howardlau1999** [comment]
感谢您的反馈，我们将检查并加入您的客户端，加入后会关闭issue
________________________________

**Comment by howardlau1999** [comment]
> ~因为我在用3.5.5（逃~
> 3.5.5许多pt站都支持，希望能把这个版本支持一下

请提供一下

peer_id 和 user_agent

**Comment by inntechy** [comment]
UA : `uTorrent/355(111915347)(45395)`
请问如何查看peer_id?

**Comment by howardlau1999** [comment]
> UA : `uTorrent/355(111915347)(45395)`
> 请问如何查看peer_id?

我查了一下access log查到了，已经添加到客户端列表里，请帮忙检查一下是否能正常使用了

**Comment by inntechy** [comment]
> 我查了一下access log查到了，已经添加到客户端列表里，请帮忙检查一下是否能正常使用了

还是不行，`非法客户端，请到6.21weeks.icu/faq.php#id29查看允许客户端列表!`

**Comment by howardlau1999** [comment]
请加入一下SYSPT用户QQ群1009541180一起帮忙排查一下

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: inntechy<mailto:notifications@github.com>
发送时间: 2019年12月23日 8:57
收件人: sysu-ipv6/sysupt<mailto:sysupt@noreply.github.com>
抄送: Howard Lau<mailto:howardlau1999@hotmail.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [sysu-ipv6/sysupt] 希望将μtorrent 3.5.5加入允许列表 (#16)


我查了一下access log查到了，已经添加到客户端列表里，请帮忙检查一下是否能正常使用了

还是不行，非法客户端，请到6.21weeks.icu/faq.php#id29查看允许客户端列表!

―
